/** Static, dependency-free MCP App. Never interpolate article HTML or secrets
 * into this document. Content is rendered with textContent, images with HTTPS. */
export const articleWidgetHtml = String.raw`<!doctype html>
<html lang="da"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Apropos AI</title><style>
:root{color-scheme:dark;font-family:Arial,sans-serif;color:#f5f5f5;background:#080808}[hidden]{display:none!important}
*{box-sizing:border-box}body{margin:0}main{max-width:760px;margin:auto;padding:20px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #333;padding-bottom:14px;gap:12px}
header img{width:44px;height:44px}header div{display:flex;align-items:center;gap:12px}h1{font-size:28px;line-height:1.2;font-weight:500;margin:24px 0 12px}p{line-height:1.65;margin:0 0 18px}article{max-width:68ch}figure{margin:24px 0}figure img{width:100%;height:auto;border-radius:8px}figcaption,.muted{font-size:14px;color:#b0b0b0;line-height:1.5}button,input,select{font:inherit;min-height:44px;border:1px solid #555;border-radius:10px;padding:10px 14px;background:transparent;color:inherit}button{cursor:pointer}button:disabled{opacity:.45;cursor:default}button:hover:not(:disabled){background:#222}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid white;outline-offset:3px}.primary{background:#eee;color:#080808}.primary:hover:not(:disabled){background:white}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}details{border-top:1px solid #333;padding-top:16px;margin:18px 0}summary{min-height:44px;cursor:pointer}label{display:block;margin:16px 0}label select,label input{display:block;width:100%;margin-top:8px}option{background:#111;color:white}.notice{border-left:2px solid #aaa;padding-left:12px}a{color:inherit}#settings[hidden],#confirm[hidden]{display:none}#status{white-space:pre-wrap}pre{white-space:pre-wrap;font:inherit;line-height:1.5;font-size:14px}
@media(max-width:440px){main{padding:16px}h1{font-size:25px}.actions button{flex:1}header span{font-size:15px}}
</style></head><body><main>
<header><div><img src="https://ai.aproposmagazine.com/images/apropos-ai-icon.png" alt=""><span>Apropos AI</span></div><button id="gear" aria-label="Detaljer og indstillinger" aria-expanded="false">⚙</button></header>
<p id="status" role="status" aria-live="polite" class="muted">Henter artiklen …</p>
<h1 id="title"></h1><p id="subtitle"></p><p id="byline" class="muted"></p>
<div id="cover"></div><article id="article"></article>
<section id="questions" aria-label="Manglende valg"></section>
<div class="actions"><button id="edit">Ret tekst</button><button id="media">Vælg billeder</button><button id="refresh">Opdatér status</button></div>
<p id="notice" class="notice"></p>
<section id="confirm" hidden><label id="scheduleLabel">Udgivelse<select id="schedule"><option value="now">Nu</option><option value="later">Planlæg</option></select></label><label id="dateLabel" hidden>Tidspunkt i København<input id="date" type="datetime-local"></label><p id="price"></p><button id="approve" class="primary"></button></section>
<section id="settings" hidden><details open><summary>Omkostninger og gemt arbejde</summary><pre id="details"></pre><button id="costs">Vis registreret forbrug</button></details><details><summary>Fortsæt i en anden chat</summary><pre id="handoff"></pre></details><a id="fallback" target="_blank" rel="noopener noreferrer">Åbn på Apropos</a></section>
</main><script>
let data=null, confirmation=null, imagePreviews={}, busy=false, ready=false, serial=0;const pending=new Map();
const el=id=>document.getElementById(id);const text=(id,value)=>el(id).textContent=value||'';
function request(method,params){return new Promise((resolve,reject)=>{const id=++serial;const timer=setTimeout(()=>{pending.delete(id);reject(Error('Forbindelsen kunne ikke bekræftes. Opdatér status før et nyt forsøg.'));},20000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');});}
async function call(name,args){const result=ready?await request('tools/call',{name,arguments:args}):window.openai?.callTool?await window.openai.callTool(name,args):await request('tools/call',{name,arguments:args});if(result?.isError)throw Error('Handlingen blev ikke bekræftet. Dit arbejde er bevaret. Opdatér status.');return result;}
function image(container,url,alt,caption){try{if(new URL(url).protocol!=='https:')return;}catch{return;}const figure=document.createElement('figure'),img=document.createElement('img');img.src=imagePreviews[url]||url;img.alt=alt||'';img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{confirmation=null;el('confirm').hidden=true;text('notice','Et billede kunne ikke vises. Opdatér preview før godkendelse.');};figure.append(img);if(caption){const label=document.createElement('figcaption');label.textContent=caption;figure.append(label);}container.append(figure);}
function receive(result){if(!result?.structuredContent?.submissionId)return;data=result.structuredContent;confirmation=result._meta?.confirmation||null;imagePreviews=result._meta?.imagePreviews||{};render();}
function render(){text('title',data.title);text('subtitle',data.article.subtitle);text('byline',[data.article.author,data.article.category].filter(Boolean).join(' · '));
const labels={awaiting_answers:'Mangler dine valg',awaiting_preparation:'Kladde',processing:'Slutkontroller er sat i kø',blocked:'Kræver opfølgning',prepared:'Klar til din godkendelse',scheduled:'Planlagt på serveren',published:data.publicationVerified?'Publiceret og verificeret på livesiden':'Registreret udgivet · livesiden er endnu ikke genbekræftet'};text('status',labels[data.status]||data.status);
el('cover').replaceChildren();if(data.article.featuredImage)image(el('cover'),data.article.featuredImage,data.article.featuredImageAlt,data.article.fotoCredit);
el('article').replaceChildren();if(data.article.intro){const p=document.createElement('p');p.textContent=data.article.intro.replace(/<[^>]*>/g,' ');el('article').append(p);}
for(const block of data.blocks||[]){if(block.kind==='image')image(el('article'),block.url,block.alt,block.caption);else{const p=document.createElement('p');p.textContent=block.text;el('article').append(p);}}
el('questions').replaceChildren();for(const q of data.questions||[]){const label=document.createElement('label');label.textContent=q.question;const input=document.createElement(q.options?'select':'input');input.dataset.field=q.field;if(q.options){const empty=document.createElement('option');empty.value='';empty.textContent='Vælg';input.append(empty);for(const opt of q.options){const option=document.createElement('option');option.value=opt.value;option.textContent=opt.label;input.append(option);}}label.append(input);el('questions').append(label);}
if(data.questions?.length){const save=document.createElement('button');save.textContent='Gem mine valg';save.onclick=()=>work(async()=>{const article={},choices={};for(const field of el('questions').querySelectorAll('[data-field]')){if(!field.value)continue;if(['kind','media'].includes(field.dataset.field))choices[field.dataset.field]=field.value;else article[field.dataset.field]=field.dataset.field==='rating'?Number(field.value):field.value;}await call('update_submission',{submissionId:data.submissionId,expectedRevision:data.revision,requestId:'answers-'+crypto.randomUUID(),article,choices});await refresh();});el('questions').append(save);}
const missing=(data.missing||[]).join(', ');text('notice',data.dependencyError||data.previewProblems?.[0]||data.blocker||(data.quote?.provider?.blocked?'Betalte slutkontroller er blokeret hos udbyderen. Tekst og billeder kan stadig gemmes.':missing?'Mangler: '+missing:''));
el('confirm').hidden=!confirmation;el('scheduleLabel').hidden=confirmation?.action!=='publish';el('dateLabel').hidden=confirmation?.action!=='publish'||el('schedule').value!=='later';text('price',confirmation?.action==='checks'?'Kun slutkontroller. Estimat '+data.quote.estimateDkk.toLocaleString('da-DK')+' kr. Maksimal reservation '+(data.quote.ceilingDkkMicros/1e6).toLocaleString('da-DK')+' kr. Ingen nye billeder eller omskrivning.':'Du godkender præcis den viste artikelversion. Ingen Instagram eller sitepublicering.');text('approve',confirmation?.action==='checks'?'Acceptér pris og kør slutkontroller':'Godkend udgivelse');
text('details',JSON.stringify({version:data.revision,quote:data.quote,savedSteps:data.savedSteps},null,2));text('handoff',JSON.stringify({title:data.title,...data.handoff,blocker:data.blocker},null,2));el('fallback').href=data.fallbackUrl;}
async function work(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){text('status',e.message||'Læs status før næste forsøg.');}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function refresh(){if(data)receive(await call('preview_submission',{submissionId:data.submissionId}));}
async function message(prompt){if(ready)return request('ui/message',{role:'user',content:[{type:'text',text:prompt}]});if(window.openai?.sendFollowUpMessage)return window.openai.sendFollowUpMessage({prompt});throw Error('Skriv din rettelse i chatten.');}
el('refresh').onclick=()=>work(refresh);el('gear').onclick=()=>{el('settings').hidden=!el('settings').hidden;el('gear').setAttribute('aria-expanded',String(!el('settings').hidden));};el('schedule').onchange=()=>{el('dateLabel').hidden=el('schedule').value!=='later';};
el('edit').onclick=()=>work(()=>message('Jeg vil rette teksten i artikel '+data.submissionId+'. Vis mig muligheder for en målrettet rettelse. Bevar billeder og øvrige felter.'));
el('media').onclick=()=>work(()=>message('Vis billedvalg til artikel '+data.submissionId+'. Genbrug gemte billeder. Film/TV skal have officielle stills. Illustrationer skal laves i chatten fra get_image_brief, ikke gennem betalt API.'));
el('costs').onclick=()=>work(async()=>{const result=await call('get_submission_costs',{submissionId:data.submissionId});text('details',result.content?.find(c=>c.type==='text')?.text||'Forbrug kunne ikke læses.');});
el('approve').onclick=()=>work(async()=>{if(!confirmation||Date.now()>=confirmation.expiresAt)throw Error('Previewet er udløbet. Opdatér status.');const localTime=confirmation.action==='publish'&&el('schedule').value==='later'?el('date').value:'now';if(!localTime)throw Error('Vælg et tidspunkt.');await call('confirm_submission_action',{token:confirmation.token,localTime});confirmation=null;el('confirm').hidden=true;await refresh();});
window.addEventListener('message',event=>{if(event.source!==window.parent||event.data?.jsonrpc!=='2.0')return;const m=event.data;if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='ui/notifications/tool-result')receive(m.params);else if(m.method==='ui/notifications/tool-cancelled')text('status','Handlingen blev afbrudt. Intet er godkendt.');});
request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'Apropos AI',version:'1.0.0'},appCapabilities:{}}).then(()=>{ready=true;window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized'},'*');}).catch(()=>{});
function compatibility(){const o=window.openai;if(!o?.toolOutput)return;const meta=o.toolResponseMetadata;receive({structuredContent:o.toolOutput,_meta:meta?.mcp_tool_result?._meta||meta?.call_tool_result?._meta||meta?._meta||meta});}
compatibility();window.addEventListener('openai:set_globals',compatibility);
let lastHeight=0;new ResizeObserver(()=>{const height=Math.ceil(document.documentElement.scrollHeight);if(height===lastHeight)return;lastHeight=height;if(ready)window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/size-changed',params:{height}},'*');}).observe(document.body);
</script></body></html>`;
