/** Public, versioned onboarding. No user/article data goes into the video. */
export const MCP_WELCOME_VERSION = '2026-10-06-v1';
export const MCP_WELCOME_URL = 'https://ai.aproposmagazine.com/connect/chatgpt/welcome';
export const MCP_WELCOME_VIDEO = '/onboarding/apropos-ai-2026-10-06.mp4';
export const MCP_WELCOME_POSTER = '/onboarding/apropos-ai-2026-10-06.jpg';
export const MCP_STARTER_PROMPTS = [
  'Vis mine seneste kladder, og fortæl kort, hvad de mangler.',
  'Forkort introen. Bevar resten af teksten og alle billeder. Vis ændringen først.',
  'Hent Apropos-billedprompten til dette afsnit, så vi kan lave illustrationen her i chatten.',
] as const;

export function mcpWelcomeContent() {
  const subject = 'Apropos AI er forbundet. Se, hvad du kan nu.';
  const text = `Velkommen til Apropos AI i ChatGPT.\n\nDin personlige forbindelse er aktiveret. Se den korte introduktion:\n${MCP_WELCOME_URL}\n\nPrøv i en chat med Apropos AI valgt:\n${MCP_STARTER_PROMPTS.map(x => `• ${x}`).join('\n')}\n\nDu kan læse og rette dine kladder, få hjælp til billedvalg og SEO samt klargøre en bestemt artikelversion til godkendelse. Film og TV bruger officielle stills. Illustrationer kan laves i ChatGPT med Apropos' prompt.\n\nNye chatforløb bestiller ikke automatisk betalt research, tekst eller billeder. Nødvendige API-slutkontroller kræver en særskilt prisaccept. Publicering kræver din godkendelse, og mangler/blokeringer skal løses først. Dit ChatGPT-abonnements funktioner og grænser gælder stadig.\n\nMailen sendes én gang efter aktivering, ikke ved hver login eller genforbindelse. Administrér din forbindelse: https://ai.aproposmagazine.com/connect/chatgpt\n\nApropos Magazine`;
  const html = `<!doctype html><html lang="da"><body style="margin:0;background:#080808;color:#f5f5f5;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="560" style="max-width:100%;width:100%"><tr><td><img src="https://ai.aproposmagazine.com/images/apropos-ai-icon.png" width="64" height="64" alt="Apropos Magazine"><h1 style="font-size:30px;font-weight:500;line-height:1.2">Din redaktion. Nu i chatten.</h1><p style="line-height:1.6;color:#ccc">Apropos AI er forbundet. Her er din korte introduktion.</p><a href="${MCP_WELCOME_URL}"><img src="https://ai.aproposmagazine.com${MCP_WELCOME_POSTER}" width="560" style="width:100%;height:auto;border:1px solid #444;border-radius:12px" alt="Se introduktionsvideoen til Apropos AI"></a><p><a href="${MCP_WELCOME_URL}" style="display:inline-block;padding:16px 24px;background:#fff;color:#080808;border-radius:10px;text-decoration:none">Se video og kom i gang</a></p><h2 style="font-size:20px;font-weight:500">Start med én sætning</h2><p style="line-height:1.6">“${MCP_STARTER_PROMPTS[0]}”</p><p style="line-height:1.6;color:#ccc">Vælg Apropos AI i chatten. Hent kladder, ret enkelte afsnit, vælg billeder og klargør til godkendelse.</p><p style="line-height:1.6;color:#ccc">Nødvendige API-slutkontroller kræver prisaccept. Intet publiceres uden din godkendelse. Mangler og blokeringer skal løses først.</p><p style="font-size:13px;line-height:1.6;color:#aaa">Én velkomst efter aktivering, ikke et nyhedsbrev. <a style="color:#ddd" href="https://ai.aproposmagazine.com/connect/chatgpt">Administrér forbindelse</a>.</p></td></tr></table></td></tr></table></body></html>`;
  return { subject, text, html };
}
