name: Daily Article Ingestion

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC (before embeddings training at 03:00)

jobs:
  ingest-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Ingest recent articles
        run: |
          echo "🔄 Starting daily article ingestion..."
          npm run ingest:rage -- --since=24 --limit=100
          echo "✅ Article ingestion completed"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          if git diff --staged --quiet; then
            echo "No new articles to commit"
          else
            git commit -m "📰 Daily article ingestion - $(date +'%Y-%m-%d')"
            git push
            echo "✅ New articles committed and pushed"
          fi
